name: snowops_intel_lite
channels:
  - snowflake
dependencies:
  - python=3.11.*
  - snowflake-snowpark-python=
  - streamlit=
  - pandas
  - altair
  - sqlparse
  - xlsxwriter
  - plotly
  - requests
